; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; Use a partition table that supports larger application size
board_build.partitions = huge_app.csv
; Add common libraries used by the firmware
lib_deps =
	knolleary/PubSubClient@^2.8
# JSON parsing library for incoming BLE config
	bblanchon/ArduinoJson@^6.19.4
# DHT22 temperature and humidity sensor
	adafruit/DHT sensor library@^1.4.6
	adafruit/Adafruit Unified Sensor@^1.1.14

